# Generated by Django 5.2.17 on 2026-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quota_bytes',
            field=models.PositiveBigIntegerField(default=52428800),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
