# Generated by Django 5.2 for cloud.nimbus.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_quota_bytes_user_reserved_bytes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"), ("bg", "Български"), ("hr", "Hrvatski"),
                    ("cs", "Čeština"), ("da", "Dansk"), ("nl", "Nederlands"),
                    ("en", "English"), ("et", "Eesti"), ("fi", "Suomi"),
                    ("fr", "Français"), ("de", "Deutsch"), ("el", "Ελληνικά"),
                    ("hu", "Magyar"), ("ga", "Gaeilge"), ("it", "Italiano"),
                    ("lv", "Latviešu"), ("lt", "Lietuvių"), ("mt", "Malti"),
                    ("pl", "Polski"), ("pt", "Português"), ("ro", "Română"),
                    ("sk", "Slovenčina"), ("sl", "Slovenščina"), ("es", "Español"),
                    ("sv", "Svenska"), ("ar", "العربية"), ("ur", "اردو"),
                    ("hi", "हिन्दी"),
                ],
                default="ru",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ui_theme",
            field=models.CharField(
                choices=[("dark", "Тёмная"), ("light", "Светлая")],
                default="dark",
                max_length=5,
            ),
        ),
    ]
