# Generated by Django 5.2.17 on 2026-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passkey_risk_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
