# Generated by Django 5.2.17 on 2026-09-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkeyreset',
            name='telegram_user_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
