# Generated by Django 5.2.17 on 2026-09-26 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='scan_report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('clean', 'Проверен'), ('infected', 'В карантине'), ('error', 'Сканер недоступен')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('total_size', models.PositiveBigIntegerField()),
                ('chunk_size', models.PositiveIntegerField()),
                ('received_parts', models.JSONField(default=list)),
                ('backend', models.CharField(choices=[('local', 'Локальные части'), ('gateway', 'Go storage gateway'), ('s3', 'S3 multipart')], default='local', max_length=20)),
                ('backend_upload_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('uploading', 'Загрузка'), ('assembling', 'Сборка'), ('complete', 'Завершена'), ('aborted', 'Отменена'), ('failed', 'Ошибка')], db_index=True, default='uploading', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'state', 'expires_at'], name='drive_uploa_owner_i_842864_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('owner', 'idempotency_key'), name='unique_upload_idempotency_key')],
            },
        ),
    ]
