# Generated by Django 5.2.17 on 2026-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_storedfile_checksum_sha256_storedfile_scan_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='provider_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Локальное хранилище'), ('s3', 'S3-совместимое хранилище'), ('gateway', 'Go storage gateway')], db_index=True, default='local', max_length=20),
        ),
    ]
