# Generated by Django 5.2.17 on 2026-09-26 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_folder_storedfile_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='upload_sessions', to='drive.folder'),
        ),
    ]
