# Generated by Django 5.2.17 on 2026-09-28 00:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipherfile',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cipherfile',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CipherFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField()),
                ('starred', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vaults.cipherfolder')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='vaults.vault')),
            ],
        ),
        migrations.AddField(
            model_name='cipherfile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='vaults.cipherfolder'),
        ),
    ]
