# Generated by Django 5.2.17 on 2026-09-26 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0002_storedfile_checksum_sha256_storedfile_scan_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактирование')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='drive.storedfile')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_file_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email', 'user_id'],
                'indexes': [models.Index(fields=['file', 'role'], name='sharing_fil_file_id_51b2fe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='sharing_grant_has_recipient'), models.UniqueConstraint(fields=('file', 'user'), name='sharing_unique_file_user_grant'), models.UniqueConstraint(fields=('file', 'email'), name='sharing_unique_file_email_grant')],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_mode', models.CharField(choices=[('anyone', 'Любой по ссылке'), ('signed_in', 'Только после входа'), ('password', 'Вход и пароль ссылки'), ('restricted', 'Только приглашённые')], default='anyone', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='drive.storedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'file', 'active'], name='sharing_sha_owner_i_a216ad_idx')],
            },
        ),
    ]
