# Generated by Django 5.2.17 on 2026-09-26 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_uploadsession_folder'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filegrant',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='drive.folder'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='filegrant',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='drive.storedfile'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='drive.storedfile'),
        ),
        migrations.AddIndex(
            model_name='filegrant',
            index=models.Index(fields=['folder', 'role'], name='sharing_fil_folder__c56832_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['owner', 'folder', 'active'], name='sharing_sha_owner_i_f5f396_idx'),
        ),
        migrations.AddConstraint(
            model_name='filegrant',
            constraint=models.UniqueConstraint(fields=('folder', 'user'), name='sharing_unique_folder_user_grant'),
        ),
        migrations.AddConstraint(
            model_name='filegrant',
            constraint=models.UniqueConstraint(fields=('folder', 'email'), name='sharing_unique_folder_email_grant'),
        ),
        migrations.AddConstraint(
            model_name='filegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='sharing_grant_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='sharing_link_exactly_one_target'),
        ),
    ]
